In [2]:
import numpy as np

## 一次元配列

In [25]:
a = np.array([1, 2, 3])

In [26]:
a

array([1, 2, 3])

In [27]:
print(a)

[1 2 3]


In [6]:
type(a)

numpy.ndarray

## shapeで、一次元配列の形状がわかる(行数, )

In [7]:
a.shape

(3,)

## 二次元配列

### shapeで、二次元配列の形状がわかる(行数, 列数)

In [8]:
b = np.array([[1, 2, 3],[4, 5, 6]])

In [9]:
b.shape

(2, 3)

## 変形

In [10]:
c1 = a = np.array([0, 1, 2, 3, 4, 6])

In [11]:
c1

array([0, 1, 2, 3, 4, 6])

### reshape　指定した次元の配列を作成する

In [12]:
c2 = c1.reshape((2, 3))

In [13]:
c2

array([[0, 1, 2],
       [3, 4, 6]])

### ravel 多次元配列を一次元配列にする (参照を返す)

In [14]:
c3 = c2.ravel()

In [15]:
c3

array([0, 1, 2, 3, 4, 6])

In [16]:
x = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

In [ ]:
x1 = x.ravel()

In [19]:
x1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
x2 = x1.reshape(3, 3)

In [21]:
x2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### flatten　多次元配列を一次元配列にする (copyを返す)

In [22]:
c4 = c2.flatten()

In [23]:
c4

array([0, 1, 2, 3, 4, 6])

## データ型

In [29]:
a.dtype

dtype('int64')

### 型(dtype)を指定して配列を作成する

In [31]:
d = np.array([1, 2], dtype=np.int16)

In [32]:
d

array([1, 2], dtype=int16)

In [33]:
d.dtype

dtype('int16')

### astype 型(dtype)を変換する

In [34]:
d.astype(np.float16)

array([1., 2.], dtype=float16)

## インデックスとスライス

In [35]:
a

array([1, 2, 3])

### インデックス

In [36]:
a[0]

np.int64(1)

### スライス

In [37]:
a[0:]

array([1, 2, 3])

In [38]:
a[-1]

np.int64(3)

In [39]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
b[0]

array([1, 2, 3])

In [42]:
b[1, 0]

np.int64(4)

In [41]:
b[:, 2]

array([3, 6])

In [43]:
b[1, :]

array([4, 5, 6])

In [44]:
b[0, 1:]

array([2, 3])

In [45]:
b[:, [0, 2]]

array([[1, 3],
       [4, 6]])

## データ再代入

In [46]:
a

array([1, 2, 3])

In [47]:
a[2] = 4

In [48]:
a

array([1, 2, 4])

In [49]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
b[1, 2] = 7

In [51]:
b

array([[1, 2, 3],
       [4, 5, 7]])

In [52]:
b[:, 2] = 8; b

array([[1, 2, 8],
       [4, 5, 8]])

## 参照とコピー(copy)

### 参照

In [53]:
a1 = a; a1

array([1, 2, 4])

In [54]:
a1[1] = 5; a1

array([1, 5, 4])

In [55]:
a

array([1, 5, 4])

### コピー

In [57]:
a2 = a.copy(); a2

array([1, 5, 4])

In [58]:
a2[0] = 6; a2

array([6, 5, 4])

In [59]:
a

array([1, 5, 4])

In [60]:
c2

array([[0, 1, 2],
       [3, 4, 6]])

### ravelとflattenの違い

In [66]:
c3 = c2.ravel() # reference
c4 = c2.flatten() # copy
c3[0] = 6
c4[1] = 7

In [67]:
c3

array([6, 1, 2, 3, 4, 6])

In [68]:
c4

array([6, 7, 2, 3, 4, 6])

In [69]:
c2

array([[6, 1, 2],
       [3, 4, 6]])

### Python標準とNumPyの違い

In [73]:
# python list
py_list1 = [0, 1]
py_list2 = py_list1[:] # copyが渡される
py_list2[0] = 2

print(py_list1)
print(py_list2)
print(py_list1)

[0, 1]
[2, 1]
[0, 1]


In [74]:
# NumPyのlist(ndarray)
np_array1 = np.array([0, 1])
np_array2 = np_array1[:] # 参照が渡される
np_array2[0] = 2

print(np_array1)
print(np_array2)
print(np_array1)

[2 1]
[2 1]
[2 1]


## 数列を返す(arange)

In [75]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

## 乱数

In [78]:
# 最新のRandomGenerator
rng = np.random.default_rng()
f = rng.random((3, 2))
f

array([[0.35705231, 0.66430263],
       [0.21499038, 0.97099979],
       [0.74212465, 0.2260753 ]])

In [79]:
rng = np.random.default_rng(123) # シード値:123
f = rng.random((3, 2))
f

array([[0.68235186, 0.05382102],
       [0.22035987, 0.18437181],
       [0.1759059 , 0.81209451]])

**シード値とは？**

In [80]:
rng = np.random.default_rng(123)
rng.integers(1, 10)

np.int64(1)

### integersから２次元配列を作成できる

In [84]:
rng = np.random.default_rng(123)
rng.integers(1, 10, size=(3, 3))

array([[1, 7, 6],
       [1, 9, 2],
       [3, 2, 4]])

In [85]:
rng = np.random.default_rng(123)
rng.uniform(0.0, 5.0, size=(2, 3))

array([[3.41175932, 0.26910509, 1.10179936],
       [0.92185905, 0.87952951, 4.06047253]])

In [87]:
rng = np.random.default_rng(123)
rng.uniform(size=(4, 3))

array([[0.68235186, 0.05382102, 0.22035987],
       [0.18437181, 0.1759059 , 0.81209451],
       [0.923345  , 0.2765744 , 0.81975456],
       [0.88989269, 0.51297046, 0.2449646 ]])

In [88]:
rng = np.random.default_rng(123)
rng.standard_normal(size=(4, 2))

array([[-0.98912135, -0.36778665],
       [ 1.28792526,  0.19397442],
       [ 0.9202309 ,  0.57710379],
       [-0.63646365,  0.54195222]])

In [89]:
rng = np.random.default_rng(123)
rng.normal(50, 10, 3)

array([40.1087865 , 46.32213349, 62.87925261])

## 同じ要素の数列を作る

In [90]:
np.zeros(3)

array([0., 0., 0.])

In [91]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [92]:
np.ones(2)

array([1., 1.])

In [93]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## 単位行列

In [94]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 指定値で埋める

In [95]:
np.full(3, 3.14)

array([3.14, 3.14, 3.14])

In [96]:
np.full((2, 4), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [97]:
np.nan

nan

In [98]:
np.array([1, 2, np.nan])

array([ 1.,  2., nan])

## 範囲指定で均等割データを作る

In [99]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [100]:
np.linspace(0, np.pi, 21)

array([0.        , 0.15707963, 0.31415927, 0.4712389 , 0.62831853,
       0.78539816, 0.9424778 , 1.09955743, 1.25663706, 1.41371669,
       1.57079633, 1.72787596, 1.88495559, 2.04203522, 2.19911486,
       2.35619449, 2.51327412, 2.67035376, 2.82743339, 2.98451302,
       3.14159265])

## 要素間の差分

In [102]:
l = np.array([2, 2, 6, 1, 3])
np.diff(l)

array([ 0,  4, -5,  2])

## 連結

### 一次元配列の場合

In [103]:
print(a)
print(a1)

[1 5 4]
[1 5 4]


In [104]:
np.concatenate([a, a1])

array([1, 5, 4, 1, 5, 4])

### 二次元配列の場合

In [105]:
b

array([[1, 2, 8],
       [4, 5, 8]])

In [106]:
b1 = np.array([[10], [20]])
b1

array([[10],
       [20]])

In [108]:
b

array([[1, 2, 8],
       [4, 5, 8]])

In [109]:
b1

array([[10],
       [20]])

### カラム方向に追加する。

In [124]:
np.concatenate([b, b1], axis=1)

array([[ 1,  2,  8, 10],
       [ 4,  5,  8, 20]])

In [111]:
np.hstack([b, b1])

array([[ 1,  2,  8, 10],
       [ 4,  5,  8, 20]])

### 行方向に追加する

In [127]:
b

array([[1, 2, 8],
       [4, 5, 8]])

In [128]:
b2 = np.array([30, 60, 45])

In [129]:
b2

array([30, 60, 45])

In [137]:
print(b.shape)
print(b2.shape)

(2, 3)
(3,)


In [134]:
np.concatenate([b, b2], axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [131]:
b3 = np.vstack([b, b2])

In [138]:
b3

array([[ 1,  2,  8],
       [ 4,  5,  8],
       [30, 60, 45]])

## 分割

２次元配列の分割方法

In [122]:
first, second = np.hsplit(b3, [2])

In [139]:
first

array([[ 1,  2],
       [ 4,  5],
       [30, 60]])

In [140]:
second

array([[ 8],
       [ 8],
       [45]])

In [144]:
first1, second1 = np.vsplit(b3, [2])

In [145]:
first1

array([[1, 2, 8],
       [4, 5, 8]])

In [146]:
second1

array([[30, 60, 45]])

## 転置

二次元配列の転置方法。
転置とは、行と列を入れ替えること。

In [147]:
b

array([[1, 2, 8],
       [4, 5, 8]])

In [148]:
b.T

array([[1, 4],
       [2, 5],
       [8, 8]])

## 次元追加

In [149]:
a

array([1, 5, 4])

In [152]:
# 行方向に次元を追加する
a[np.newaxis, :]

array([[1, 5, 4]])

In [153]:
# 列方向に次元を追加する
a[:, np.newaxis]

array([[1],
       [5],
       [4]])

## グリッドデータの生成

meshgridは２次元上の点に対応する等高線やヒートマップなどを描くときに使用する。

In [155]:
m = np.arange(0, 4); m

array([0, 1, 2, 3])

In [167]:
n = np.arange(4, 7); n

array([4, 5, 6])

In [168]:
# mとnを、それぞれ行方向と列方向に方眼常（グリッド）のデータを作成する。
xx, yy = np.meshgrid(m, n)

In [169]:
# 行方向
xx

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [170]:
# 列方向
yy

array([[4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6]])