# NumPyの各機能

In [1]:
import numpy as np

In [3]:
a = np.arange(3)
b = np.arange(-3, 3).reshape((2, 3))
c = np.arange(1, 7).reshape((2, 3))
d = np.arange(6).reshape((3, 2))
e = np.linspace(-1, 1, 10)

In [5]:
print("a:", a)
print("b:", b)
print("c:", c)
print("d:", d)
print("e:", e)

a: [0 1 2]
b: [[-3 -2 -1]
 [ 0  1  2]]
c: [[1 2 3]
 [4 5 6]]
d: [[0 1]
 [2 3]
 [4 5]]
e: [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]


In [4]:
print("a:", a.shape)
print("b:", b.shape)
print("c:", c.shape)
print("d:", d.shape)
print("e:", e.shape)

a: (3,)
b: (2, 3)
c: (2, 3)
d: (3, 2)
e: (10,)


In [19]:
print("a:", a.dtype)
print("b:", b.dtype)
print("c:", c.dtype)
print("d:", d.dtype)
print("e:", e.dtype)

a: int64
b: int64
c: int64
d: int64
e: float64


In [20]:
print("a:", type(a))
print("b:", type(b))
print("c:", type(c))
print("d:", type(d))
print("e:", type(e))

a: <class 'numpy.ndarray'>
b: <class 'numpy.ndarray'>
c: <class 'numpy.ndarray'>
d: <class 'numpy.ndarray'>
e: <class 'numpy.ndarray'>


## ユニバーサルファンクション

In [6]:
li = [[-3, -2, -1],
      [0, 1, 2]]
new =[]
for i, j in enumerate(li):
    new.append([])
    for k in j:
        new[i].append(abs(k))

new

[[3, 2, 1], [0, 1, 2]]

In [7]:
np.abs(b)

array([[3, 2, 1],
       [0, 1, 2]])

In [8]:
np.sin(e)

array([-0.84147098, -0.70169788, -0.52741539, -0.3271947 , -0.11088263,
        0.11088263,  0.3271947 ,  0.52741539,  0.70169788,  0.84147098])

In [9]:
np.cos(e)

array([0.54030231, 0.71247462, 0.84960756, 0.94495695, 0.99383351,
       0.99383351, 0.94495695, 0.84960756, 0.71247462, 0.54030231])

In [10]:
np.log(a)

/tmp/ipykernel_1063/176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718])

In [11]:
np.log10(c)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125]])

In [12]:
np.exp(a)

array([1.        , 2.71828183, 7.3890561 ])

In [13]:
a

array([0, 1, 2])

In [14]:
a + 10

array([10, 11, 12])

In [15]:
b

array([[-3, -2, -1],
       [ 0,  1,  2]])

In [16]:
a + b

array([[-3, -1,  1],
       [ 0,  2,  4]])

In [17]:
a1 = a[:, np.newaxis]; a1

array([[0],
       [1],
       [2]])

In [18]:
a + a1

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])